version: 2.1

parameters:
  circleci-changed:
    type: boolean
    default: false
  run-ci-rust:
    type: boolean
    default: false

orbs:
  aws-ecr: circleci/aws-ecr@7.2.0

jobs:

  no-jobs:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: |
          echo "Nothing to do!"


  ci-rust-build:
    executor: aws-ecr/default
    steps:
      - aws-ecr/build-and-push-image:
          #setup-remote-docker: true
          #remote-docker-layer-caching: true
          path: ci-rust
          repo: ci-rust
          create-repo: true
          tag: build-<< pipeline.git.revision >>


  ci-rust-test:
    docker:
      - image: 014428637873.dkr.ecr.us-east-1.amazonaws.com/ci-rust:build-<< pipeline.git.revision >>
    steps:
      - run: |
          cargo --version
          cargo new hello
          cd hello
          cargo run
          just --version


  ci-rust-deploy:
    executor: aws-ecr/default
    steps:
      - aws-ecr/build-and-push-image:
          #setup-remote-docker: true
          #remote-docker-layer-caching: true
          path: ci-rust
          repo: ci-rust
          tag: latest


workflows:
  version: 2

  nothing:
    when:
      or: [not: << pipeline.parameters.run-ci-rust >>, not: << pipeline.parameters.circleci-changed >>]
    jobs:
      - no-jobs

  ci-rust:
    when: 
      or: [<< pipeline.parameters.run-ci-rust >>, << pipeline.parameters.circleci-changed >>]
    jobs:
      - ci-rust-build:
          context: [aws] 
      - ci-rust-test:
          context:  [aws] 
          requires: [ci-rust-build]
      - ci-rust-deploy:
          context:  [aws] 
          requires: [ci-rust-test]
          filters:
             branches:
               only: main